name: lista_de_la_compra
description: "Una aplicación para gestionar la lista de la compra"
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.3.6+11

environment:
  sdk: ^3.9.2
  flutter: 3.44.8

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter
  
  provider: 6.1.5+1

  lista_de_la_compra_backend:
    path: ../packages/lista_de_la_compra_backend
  flutter_show_when_locked: 1.0.0
  flutter_localizations:
    sdk: flutter
  nsd: 5.0.1
  contentsize_tabbarview: 0.0.2
  share_plus: ^13.2.0
  fluttertoast: 9.1.0
  device_marketing_names: ^2.0.2
  shared_preferences: 2.5.5


  drift_flutter: ^0.3.1
  file_picker: ^12.0.0-beta.7
  intl: 0.20.2
  path_provider: ^2.1.6

  web_socket_channel: ^3.0.3

  collection: 1.19.1
  uuid: 4.5.3
dev_dependencies:
  drift_dev: 2.34.4
  flutter_lints: ^6.0.0
  build_runner: ^2.15.0
  # We use this to compile the shared web worker for the web database. This dependency
  # isn't required for most apps. You only need it if you want to target the web, use
  # web workers for drift AND want to compile those web workers through `build_runner`.
  # Either way, using this package with Flutter requires a delicate setup described in
  # `build.yaml`.
  build_web_compilers: 4.8.0
  build: ^4.0.7

flutter:
  uses-material-design: true
  generate: true