
name: "Fastline Check"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  pull_request:
    branches:
      - master
      - develop
      
jobs:  
  build:  
    name: Check form
    runs-on: ubuntu-latest 
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Validate Fastlane Supply Metadata
      uses: ashutoshgngwr/validate-fastlane-supply-metadata@v2.1.0
